"""Type stubs for the Rust extension module `timewarp._timewarp`."""

def sum_as_string(a: int, b: int) -> str: ...
def sum_as_int(a: int, b: int) -> int: ...
def intersection(a: tuple[int, int], b: tuple[int, int]) -> tuple[int, int] | None: ...
